# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: vinodjalagam/frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: REACT_APP_URL
              value: http://backend:5050/record

---
# Frontend Service
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: mern-app
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 31000
      protocal: TCP
